server:
  # 端口号
  port: 8080

spring:
  # mysql连接配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/FxBlog
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间
    timeout: 5000
  # 静态资源配置
  web:
    resources:
      static-locations: file:./json,
  mvc:
    static-path-pattern: /**

logging:
  file:
    # 日志路径
    path: D:/Work/JAVA/FxBlog/log
  level:
    # 将mapper接口所在包的logger等级改为debug,以打印sql语句
    com.example.fxblog.mapper: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fxblog.entity
  # MyBatis 原生支持的配置
  configuration:
    map-underscore-to-camel-case: true
