server:
  # 端口号
  port: 443
  ssl:
    key-store: classpath:6718648.pfx
    key-store-password: M2gVaYTf
    key-store-type: PKCS12

spring:
  # mysql连接配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/FxBlog
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    # 连接超时时间
    timeout: 5000
  mvc:
    static-path-pattern: /**
  # jackson统一时间处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  config:
    activate:
      on-profile: dev

logging:
  level:
    # 将mapper接口所在包的logger等级改为debug,以打印sql语句
    com.example.fxblog.mapper: debug
  file:
    # 日志路径
    path: D:/Work/JAVA/FxBlog/log

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fxblog.entity
  # MyBatis 原生支持的配置
  configuration:
    map-underscore-to-camel-case: true
